"""Create Role Table

Revision ID: 1d30487b6c5e
Revises: 66116e0a12dd
Create Date: 2020-09-18 16:34:00.186957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d30487b6c5e'
down_revision = '66116e0a12dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role = op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    roles_parents = op.create_table('roles_parents',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )

    op.bulk_insert(role,
        [
            {'id':1, 'name':'admin'},
            {'id':2, 'name':'superuser'},
            {'id':3, 'name':'user'},
        ]
    )
    op.bulk_insert(roles_parents,
        [
            {'role_id':2, 'parent_id': 1},
            {'role_id':3, 'parent_id': 2},
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('roles_parents')
    op.drop_table('role')
    # ### end Alembic commands ###
